/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Filter applied to the categories dataset. The condition property is required for every filter except the final filter.
*/
export class AlissCategoriesFilter {
    'field': AlissCategoriesFilterFieldEnum;
    'value': string;
    'operator': AlissCategoriesFilterOperatorEnum;
    'condition'?: AlissCategoriesFilterConditionEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "AlissCategoriesFilterFieldEnum",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "AlissCategoriesFilterOperatorEnum",
            "format": ""
        },
        {
            "name": "condition",
            "baseName": "condition",
            "type": "AlissCategoriesFilterConditionEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AlissCategoriesFilter.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AlissCategoriesFilterFieldEnum {
    Name = 'name',
    Slug = 'slug',
    UnknownDefaultOpenApi = '11184809'
}
export enum AlissCategoriesFilterOperatorEnum {
    Equal = '=',
    Like = 'LIKE',
    In = 'IN',
    UnknownDefaultOpenApi = '11184809'
}
export enum AlissCategoriesFilterConditionEnum {
    And = 'AND',
    Or = 'OR',
    UnknownDefaultOpenApi = '11184809'
}

