/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Filter applied to the organisations dataset. The condition property is required for every filter except the final filter.
*/
export class AlissOrganisationsFilter {
    'field': AlissOrganisationsFilterFieldEnum;
    'value': string;
    'operator': AlissOrganisationsFilterOperatorEnum;
    'condition'?: AlissOrganisationsFilterConditionEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "AlissOrganisationsFilterFieldEnum",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "AlissOrganisationsFilterOperatorEnum",
            "format": ""
        },
        {
            "name": "condition",
            "baseName": "condition",
            "type": "AlissOrganisationsFilterConditionEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AlissOrganisationsFilter.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AlissOrganisationsFilterFieldEnum {
    Name = 'name',
    Slug = 'slug',
    UnknownDefaultOpenApi = '11184809'
}
export enum AlissOrganisationsFilterOperatorEnum {
    Equal = '=',
    Like = 'LIKE',
    In = 'IN',
    UnknownDefaultOpenApi = '11184809'
}
export enum AlissOrganisationsFilterConditionEnum {
    And = 'AND',
    Or = 'OR',
    UnknownDefaultOpenApi = '11184809'
}

