/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Filter applied to the services dataset. The condition property is required for every filter except the final filter.
*/
export class AlissServicesFilter {
    'field': AlissServicesFilterFieldEnum;
    'value': string;
    'operator': AlissServicesFilterOperatorEnum;
    'condition'?: AlissServicesFilterConditionEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "AlissServicesFilterFieldEnum",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "AlissServicesFilterOperatorEnum",
            "format": ""
        },
        {
            "name": "condition",
            "baseName": "condition",
            "type": "AlissServicesFilterConditionEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AlissServicesFilter.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AlissServicesFilterFieldEnum {
    Id = 'id',
    Name = 'name',
    Slug = 'slug',
    Description = 'description',
    UnknownDefaultOpenApi = '11184809'
}
export enum AlissServicesFilterOperatorEnum {
    Equal = '=',
    Like = 'LIKE',
    In = 'IN',
    UnknownDefaultOpenApi = '11184809'
}
export enum AlissServicesFilterConditionEnum {
    And = 'AND',
    Or = 'OR',
    UnknownDefaultOpenApi = '11184809'
}

