/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AlissAccessibilityFeature {
    'name'?: string;
    'promptquestions'?: string | null;
    'icon'?: string | null;
    'slug'?: string;
    'displayorder'?: number;
    'isVirtual'?: boolean;
    'isPhysical'?: boolean;
    'count'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "promptquestions",
            "baseName": "promptquestions",
            "type": "string",
            "format": ""
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string",
            "format": ""
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayorder",
            "baseName": "displayorder",
            "type": "number",
            "format": ""
        },
        {
            "name": "isVirtual",
            "baseName": "is_virtual",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isPhysical",
            "baseName": "is_physical",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AlissAccessibilityFeature.attributeTypeMap;
    }

    public constructor() {
    }
}
