/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AlissAccessibilityFeature } from '../models/AlissAccessibilityFeature';
import { AlissCommunityGroup } from '../models/AlissCommunityGroup';
import { AlissLocation } from '../models/AlissLocation';
import { AlissNamedSlugItem } from '../models/AlissNamedSlugItem';
import { AlissOrganisation } from '../models/AlissOrganisation';
import { AlissServiceArea } from '../models/AlissServiceArea';
import { HttpFile } from '../http/http';

export class AlissService {
    'id': string;
    'name': string;
    'description'?: string | null;
    'descriptionFormatted'?: string | null;
    'url'?: string | null;
    'referralUrl'?: string | null;
    'phone'?: string | null;
    'email'?: string | null;
    'facebook'?: string | null;
    'twitter'?: string | null;
    'instagram'?: string | null;
    'summary'?: string | null;
    'slug'?: string;
    'isClaimed'?: boolean;
    'isDeprioritised'?: boolean;
    'lastUpdated'?: string | null;
    'lastReviewed'?: string | null;
    'locationScore'?: number | null;
    'organisation'?: AlissOrganisation;
    'categories'?: Array<AlissNamedSlugItem>;
    'serviceAreas'?: Array<AlissServiceArea>;
    'locations'?: Array<AlissLocation>;
    'accessibilityFeatures'?: Array<AlissAccessibilityFeature>;
    'communityGroups'?: Array<AlissCommunityGroup>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "descriptionFormatted",
            "baseName": "description_formatted",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "referralUrl",
            "baseName": "referral_url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "facebook",
            "baseName": "facebook",
            "type": "string",
            "format": ""
        },
        {
            "name": "twitter",
            "baseName": "twitter",
            "type": "string",
            "format": ""
        },
        {
            "name": "instagram",
            "baseName": "instagram",
            "type": "string",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string",
            "format": ""
        },
        {
            "name": "isClaimed",
            "baseName": "is_claimed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isDeprioritised",
            "baseName": "is_deprioritised",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "lastUpdated",
            "baseName": "last_updated",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastReviewed",
            "baseName": "last_reviewed",
            "type": "string",
            "format": ""
        },
        {
            "name": "locationScore",
            "baseName": "location_score",
            "type": "number",
            "format": "double"
        },
        {
            "name": "organisation",
            "baseName": "organisation",
            "type": "AlissOrganisation",
            "format": ""
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<AlissNamedSlugItem>",
            "format": ""
        },
        {
            "name": "serviceAreas",
            "baseName": "service_areas",
            "type": "Array<AlissServiceArea>",
            "format": ""
        },
        {
            "name": "locations",
            "baseName": "locations",
            "type": "Array<AlissLocation>",
            "format": ""
        },
        {
            "name": "accessibilityFeatures",
            "baseName": "accessibility_features",
            "type": "Array<AlissAccessibilityFeature>",
            "format": ""
        },
        {
            "name": "communityGroups",
            "baseName": "community_groups",
            "type": "Array<AlissCommunityGroup>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AlissService.attributeTypeMap;
    }

    public constructor() {
    }
}
