/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AlissCommunityGroup {
    'displayorder'?: number;
    'id'?: string;
    'isrange'?: boolean;
    'name'?: string;
    'slug'?: string;
    'count'?: number;
    'parentId'?: string | null;
    'subCommunitygroups'?: Array<AlissCommunityGroup>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "displayorder",
            "baseName": "displayorder",
            "type": "number",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "isrange",
            "baseName": "isrange",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        },
        {
            "name": "parentId",
            "baseName": "parent_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "subCommunitygroups",
            "baseName": "sub_communitygroups",
            "type": "Array<AlissCommunityGroup>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AlissCommunityGroup.attributeTypeMap;
    }

    public constructor() {
    }
}
