/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Filter applied to the service_areas dataset. The condition property is required for every filter except the final filter.
*/
export class AlissServiceAreasFilter {
    'field': AlissServiceAreasFilterFieldEnum;
    'value': string;
    'operator': AlissServiceAreasFilterOperatorEnum;
    'condition'?: AlissServiceAreasFilterConditionEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "AlissServiceAreasFilterFieldEnum",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "AlissServiceAreasFilterOperatorEnum",
            "format": ""
        },
        {
            "name": "condition",
            "baseName": "condition",
            "type": "AlissServiceAreasFilterConditionEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AlissServiceAreasFilter.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AlissServiceAreasFilterFieldEnum {
    Id = 'id',
    Name = 'name',
    Type = 'type',
    Code = 'code',
    UnknownDefaultOpenApi = '11184809'
}
export enum AlissServiceAreasFilterOperatorEnum {
    Equal = '=',
    Like = 'LIKE',
    In = 'IN',
    UnknownDefaultOpenApi = '11184809'
}
export enum AlissServiceAreasFilterConditionEnum {
    And = 'AND',
    Or = 'OR',
    UnknownDefaultOpenApi = '11184809'
}

