/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConditionAlternateName } from '../models/ConditionAlternateName';
import { HttpFile } from '../http/http';

export class ConditionAbout {
    'type'?: string;
    'name'?: string | null;
    'alternateName'?: ConditionAlternateName;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "alternateName",
            "baseName": "alternateName",
            "type": "ConditionAlternateName",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConditionAbout.attributeTypeMap;
    }

    public constructor() {
    }
}
