/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Source content identifier.
*/
/**
 * @type ConditionVideoObjectIdentifier
 * Type
 * @export
 */
export type ConditionVideoObjectIdentifier = number | string;

/**
* @type ConditionVideoObjectIdentifierClass
    * Source content identifier.
* @export
*/
export class ConditionVideoObjectIdentifierClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

