/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConditionContentNode } from '../models/ConditionContentNode';
import { HttpFile } from '../http/http';

export class ConditionHealthTopicContent {
    'type'?: string;
    'url'?: string | null;
    'hasHealthAspect'?: string | null;
    'headline'?: string | null;
    'description'?: string | null;
    'hasPart'?: Array<ConditionContentNode>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasHealthAspect",
            "baseName": "hasHealthAspect",
            "type": "string",
            "format": ""
        },
        {
            "name": "headline",
            "baseName": "headline",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasPart",
            "baseName": "hasPart",
            "type": "Array<ConditionContentNode>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConditionHealthTopicContent.attributeTypeMap;
    }

    public constructor() {
    }
}
