/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConditionContentNode } from '../models/ConditionContentNode';
import { ConditionLinkValue } from '../models/ConditionLinkValue';
import { ConditionPotentialAction } from '../models/ConditionPotentialAction';
import { ConditionVideoObjectIdentifier } from '../models/ConditionVideoObjectIdentifier';
import { HttpFile } from '../http/http';

export class ConditionWebPageElement {
    'type'?: string | null;
    'identifier'?: ConditionVideoObjectIdentifier | null;
    'name'?: string | null;
    'position'?: number | null;
    'headline'?: string | null;
    'description'?: string | null;
    /**
    * Content text. HTML is included by default and removed when no_html is enabled.
    */
    'text'?: string | null;
    'url'?: string | null;
    'hasHealthAspect'?: string | null;
    'links'?: Array<ConditionLinkValue>;
    'potentialAction'?: ConditionPotentialAction;
    'mainEntityOfPage'?: Array<ConditionContentNode>;
    'hasPart'?: Array<ConditionContentNode>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "ConditionVideoObjectIdentifier",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number",
            "format": ""
        },
        {
            "name": "headline",
            "baseName": "headline",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasHealthAspect",
            "baseName": "hasHealthAspect",
            "type": "string",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<ConditionLinkValue>",
            "format": ""
        },
        {
            "name": "potentialAction",
            "baseName": "potentialAction",
            "type": "ConditionPotentialAction",
            "format": ""
        },
        {
            "name": "mainEntityOfPage",
            "baseName": "mainEntityOfPage",
            "type": "Array<ConditionContentNode>",
            "format": ""
        },
        {
            "name": "hasPart",
            "baseName": "hasPart",
            "type": "Array<ConditionContentNode>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConditionWebPageElement.attributeTypeMap;
    }

    public constructor() {
    }
}
