/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConditionAbout } from '../models/ConditionAbout';
import { ConditionBreadcrumb } from '../models/ConditionBreadcrumb';
import { ConditionContentNode } from '../models/ConditionContentNode';
import { ConditionHealthTopicContent } from '../models/ConditionHealthTopicContent';
import { ConditionKeywords } from '../models/ConditionKeywords';
import { ConditionOrganisation } from '../models/ConditionOrganisation';
import { ConditionRelatedLink } from '../models/ConditionRelatedLink';
import { HttpFile } from '../http/http';

/**
* An NHS Conditions page stored and returned by MRD. The structure varies between source records and may contain nested health-topic content, webpage elements and videos.
*/
export class ConditionPage {
    'context': string;
    'type': ConditionPageTypeEnum;
    'name': string;
    'copyrightHolder'?: ConditionOrganisation;
    'license'?: string | null;
    'author'?: ConditionOrganisation;
    'about'?: ConditionAbout;
    'description': string;
    /**
    * MRD URL by default or the original NHS URL when nhs_links is enabled.
    */
    'url': string;
    'genre'?: Array<string>;
    'keywords'?: ConditionKeywords;
    'dateModified'?: Date | null;
    /**
    * The last review date followed by the next review-due date when supplied.
    */
    'lastReviewed'?: Array<Date>;
    'breadcrumb'?: ConditionBreadcrumb;
    'hasPart'?: Array<ConditionHealthTopicContent>;
    'relatedLink'?: Array<ConditionRelatedLink>;
    'contentSubTypes'?: Array<string>;
    'headline'?: string | null;
    'mainEntityOfPage'?: Array<ConditionContentNode>;
    'webpage'?: string;
    'id': number;
    'routeMapping': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "context",
            "baseName": "@context",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "@type",
            "type": "ConditionPageTypeEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "copyrightHolder",
            "baseName": "copyrightHolder",
            "type": "ConditionOrganisation",
            "format": ""
        },
        {
            "name": "license",
            "baseName": "license",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "ConditionOrganisation",
            "format": ""
        },
        {
            "name": "about",
            "baseName": "about",
            "type": "ConditionAbout",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "genre",
            "baseName": "genre",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "ConditionKeywords",
            "format": ""
        },
        {
            "name": "dateModified",
            "baseName": "dateModified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastReviewed",
            "baseName": "lastReviewed",
            "type": "Array<Date>",
            "format": "date-time"
        },
        {
            "name": "breadcrumb",
            "baseName": "breadcrumb",
            "type": "ConditionBreadcrumb",
            "format": ""
        },
        {
            "name": "hasPart",
            "baseName": "hasPart",
            "type": "Array<ConditionHealthTopicContent>",
            "format": ""
        },
        {
            "name": "relatedLink",
            "baseName": "relatedLink",
            "type": "Array<ConditionRelatedLink>",
            "format": ""
        },
        {
            "name": "contentSubTypes",
            "baseName": "contentSubTypes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "headline",
            "baseName": "headline",
            "type": "string",
            "format": ""
        },
        {
            "name": "mainEntityOfPage",
            "baseName": "mainEntityOfPage",
            "type": "Array<ConditionContentNode>",
            "format": ""
        },
        {
            "name": "webpage",
            "baseName": "webpage",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "routeMapping",
            "baseName": "route_mapping",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConditionPage.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ConditionPageTypeEnum {
    MedicalWebPage = 'MedicalWebPage',
    WebPage = 'WebPage',
    UnknownDefaultOpenApi = '11184809'
}

