/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Page keywords. Depending on the source record, this can be a string or an array.
*/
/**
 * @type ConditionKeywords
 * Type
 * @export
 */
export type ConditionKeywords = Array<string> | string;

/**
* @type ConditionKeywordsClass
    * Page keywords. Depending on the source record, this can be a string or an array.
* @export
*/
export class ConditionKeywordsClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

