/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ConditionMrdLinkObject {
    'key'?: string | null;
    'mrdApiLink'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "mrdApiLink",
            "baseName": "mrd_api_link",
            "type": "string",
            "format": "uri"
        }    ];

    static getAttributeTypeMap() {
        return ConditionMrdLinkObject.attributeTypeMap;
    }

    public constructor() {
    }
}
