/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An alternate page name. The source data may return either a single string or an array of strings.
*/
/**
 * @type ConditionAlternateName
 * Type
 * @export
 */
export type ConditionAlternateName = Array<string> | string;

/**
* @type ConditionAlternateNameClass
    * An alternate page name. The source data may return either a single string or an array of strings.
* @export
*/
export class ConditionAlternateNameClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

