/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConditionExternalLinkObject } from '../models/ConditionExternalLinkObject';
import { ConditionMrdLinkObject } from '../models/ConditionMrdLinkObject';
import { HttpFile } from '../http/http';

/**
* A content link. Depending on no_html and nhs_links, links can be returned as MRD link objects, external link objects or plain URL strings.
*/
/**
 * @type ConditionLinkValue
 * Type
 * @export
 */
export type ConditionLinkValue = ConditionExternalLinkObject | ConditionMrdLinkObject | string;

/**
* @type ConditionLinkValueClass
    * A content link. Depending on no_html and nhs_links, links can be returned as MRD link objects, external link objects or plain URL strings.
* @export
*/
export class ConditionLinkValueClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}


