/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A structured filter used by the Conditions search endpoint. Every filter must contain exactly value, operator and condition.
*/
export class ConditionSearchFilter {
    /**
    * Text to search for. The value must not be empty and may contain only letters, numbers and whitespace.
    */
    'value': string;
    /**
    * Comparison operator accepted by the Conditions search validator.
    */
    'operator': ConditionSearchFilterOperatorEnum;
    /**
    * Logical condition supplied with the filter. The property is required but may be an empty string. The current validator accepts an empty string, AND or OR.
    */
    'condition': ConditionSearchFilterConditionEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "ConditionSearchFilterOperatorEnum",
            "format": ""
        },
        {
            "name": "condition",
            "baseName": "condition",
            "type": "ConditionSearchFilterConditionEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConditionSearchFilter.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ConditionSearchFilterOperatorEnum {
    Like = 'LIKE',
    UnknownDefaultOpenApi = '11184809'
}
export enum ConditionSearchFilterConditionEnum {
    Empty = '',
    And = 'AND',
    Or = 'OR',
    UnknownDefaultOpenApi = '11184809'
}

