/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConditionErrorResponse } from '../models/ConditionErrorResponse';
import { ConditionPage } from '../models/ConditionPage';
import { HttpFile } from '../http/http';

/**
* A Conditions page, an array of matching pages, or an application-level error returned by the service.
*/
/**
 * @type ConditionResponse
 * Type
 * @export
 */
export type ConditionResponse = Array<ConditionPage> | ConditionErrorResponse | ConditionPage;

/**
* @type ConditionResponseClass
    * A Conditions page, an array of matching pages, or an application-level error returned by the service.
* @export
*/
export class ConditionResponseClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}


