/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConditionHealthTopicContent } from '../models/ConditionHealthTopicContent';
import { ConditionVideoObject } from '../models/ConditionVideoObject';
import { ConditionWebPageElement } from '../models/ConditionWebPageElement';
import { HttpFile } from '../http/http';

/**
* A recursive content node. NHS Conditions records can contain webpage elements, health-topic sections and video objects.
*/
/**
 * @type ConditionContentNode
 * Type
 * @export
 */
export type ConditionContentNode = ConditionHealthTopicContent | ConditionVideoObject | ConditionWebPageElement;

/**
* @type ConditionContentNodeClass
    * A recursive content node. NHS Conditions records can contain webpage elements, health-topic sections and video objects.
* @export
*/
export class ConditionContentNodeClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}


