/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConditionErrorResponse } from '../models/ConditionErrorResponse';
import { HttpFile } from '../http/http';

/**
* Conditions records matching the supplied search filters.
*/
/**
 * @type ConditionsSearchResponse
 * Type
 * @export
 */
export type ConditionsSearchResponse = Array<ConditionPage> | ConditionErrorResponse;

/**
* @type ConditionsSearchResponseClass
    * Conditions records matching the supplied search filters.
* @export
*/
export class ConditionsSearchResponseClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

