/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CountryMaps {
    'googleMaps': string | null;
    'openStreetMaps': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "googleMaps",
            "baseName": "googleMaps",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "openStreetMaps",
            "baseName": "openStreetMaps",
            "type": "string",
            "format": "uri"
        }    ];

    static getAttributeTypeMap() {
        return CountryMaps.attributeTypeMap;
    }

    public constructor() {
    }
}
