/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CountryCapitalInfo } from '../models/CountryCapitalInfo';
import { CountryCar } from '../models/CountryCar';
import { CountryCoatOfArms } from '../models/CountryCoatOfArms';
import { CountryCurrency } from '../models/CountryCurrency';
import { CountryDemonym } from '../models/CountryDemonym';
import { CountryFlags } from '../models/CountryFlags';
import { CountryIdd } from '../models/CountryIdd';
import { CountryMaps } from '../models/CountryMaps';
import { CountryName } from '../models/CountryName';
import { CountryPostalCode } from '../models/CountryPostalCode';
import { CountryTranslation } from '../models/CountryTranslation';
import { HttpFile } from '../http/http';

/**
* Complete country record returned by an unfiltered Countries request.
*/
export class Country {
    'name': CountryName;
    'cca2': string | null;
    'cca3': string | null;
    'ccn3': string | null;
    /**
    * Whether the country is independent. The current database response serializes this as 0 or 1.
    */
    'independent': CountryIndependentEnum | null;
    'status': string | null;
    /**
    * Whether the country is a United Nations member. The current database response serializes this as 0 or 1.
    */
    'unMember': CountryUnMemberEnum | null;
    'capital': Array<string>;
    'altSpellings': Array<string>;
    'region': string | null;
    'subregion': string | null;
    /**
    * Language codes mapped to language names.
    */
    'languages': { [key: string]: string; };
    /**
    * Whether the country is landlocked. The current database response serializes this as 0 or 1.
    */
    'landlocked': CountryLandlockedEnum | null;
    'area': number | null;
    'demonyms': { [key: string]: CountryDemonym; };
    'translations': { [key: string]: CountryTranslation; };
    'flag': string | null;
    'maps': CountryMaps;
    'population': number | null;
    /**
    * Gini coefficient values keyed by year. Countries without Gini data return an empty object.
    */
    'gini': { [key: string]: number; };
    /**
    * FIFA country code. The source may also return an empty string.
    */
    'fifa': string | null;
    'car': CountryCar;
    'timezones': Array<string>;
    'continents': Array<string>;
    'flags': CountryFlags;
    'coatOfArms': CountryCoatOfArms;
    'startOfWeek': string | null;
    'capitalInfo': CountryCapitalInfo;
    'postalCode': CountryPostalCode;
    'currencies': { [key: string]: CountryCurrency; };
    'idd': CountryIdd;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "CountryName",
            "format": ""
        },
        {
            "name": "cca2",
            "baseName": "cca2",
            "type": "string",
            "format": ""
        },
        {
            "name": "cca3",
            "baseName": "cca3",
            "type": "string",
            "format": ""
        },
        {
            "name": "ccn3",
            "baseName": "ccn3",
            "type": "string",
            "format": ""
        },
        {
            "name": "independent",
            "baseName": "independent",
            "type": "CountryIndependentEnum",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "unMember",
            "baseName": "unMember",
            "type": "CountryUnMemberEnum",
            "format": ""
        },
        {
            "name": "capital",
            "baseName": "capital",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "altSpellings",
            "baseName": "altSpellings",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string",
            "format": ""
        },
        {
            "name": "subregion",
            "baseName": "subregion",
            "type": "string",
            "format": ""
        },
        {
            "name": "languages",
            "baseName": "languages",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "landlocked",
            "baseName": "landlocked",
            "type": "CountryLandlockedEnum",
            "format": ""
        },
        {
            "name": "area",
            "baseName": "area",
            "type": "number",
            "format": "double"
        },
        {
            "name": "demonyms",
            "baseName": "demonyms",
            "type": "{ [key: string]: CountryDemonym; }",
            "format": ""
        },
        {
            "name": "translations",
            "baseName": "translations",
            "type": "{ [key: string]: CountryTranslation; }",
            "format": ""
        },
        {
            "name": "flag",
            "baseName": "flag",
            "type": "string",
            "format": ""
        },
        {
            "name": "maps",
            "baseName": "maps",
            "type": "CountryMaps",
            "format": ""
        },
        {
            "name": "population",
            "baseName": "population",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "gini",
            "baseName": "gini",
            "type": "{ [key: string]: number; }",
            "format": "double"
        },
        {
            "name": "fifa",
            "baseName": "fifa",
            "type": "string",
            "format": ""
        },
        {
            "name": "car",
            "baseName": "car",
            "type": "CountryCar",
            "format": ""
        },
        {
            "name": "timezones",
            "baseName": "timezones",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "continents",
            "baseName": "continents",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "flags",
            "baseName": "flags",
            "type": "CountryFlags",
            "format": ""
        },
        {
            "name": "coatOfArms",
            "baseName": "coatOfArms",
            "type": "CountryCoatOfArms",
            "format": ""
        },
        {
            "name": "startOfWeek",
            "baseName": "startOfWeek",
            "type": "string",
            "format": ""
        },
        {
            "name": "capitalInfo",
            "baseName": "capitalInfo",
            "type": "CountryCapitalInfo",
            "format": ""
        },
        {
            "name": "postalCode",
            "baseName": "postalCode",
            "type": "CountryPostalCode",
            "format": ""
        },
        {
            "name": "currencies",
            "baseName": "currencies",
            "type": "{ [key: string]: CountryCurrency; }",
            "format": ""
        },
        {
            "name": "idd",
            "baseName": "idd",
            "type": "CountryIdd",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Country.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CountryIndependentEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_unknown_default_open_api = 11184809
}
export enum CountryUnMemberEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_unknown_default_open_api = 11184809
}
export enum CountryLandlockedEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_unknown_default_open_api = 11184809
}

