/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* International dialling information. If no dialling suffixes exist, the API returns an empty object.
*/
export class CountryIdd {
    'root'?: string | null;
    'suffixes'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "root",
            "baseName": "root",
            "type": "string",
            "format": ""
        },
        {
            "name": "suffixes",
            "baseName": "suffixes",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CountryIdd.attributeTypeMap;
    }

    public constructor() {
    }
}
