/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CountryName {
    'common': string | null;
    'official': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "common",
            "baseName": "common",
            "type": "string",
            "format": ""
        },
        {
            "name": "official",
            "baseName": "official",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CountryName.attributeTypeMap;
    }

    public constructor() {
    }
}
