/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CountryCar {
    'signs': Array<string>;
    'side': CountryCarSideEnum | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "signs",
            "baseName": "signs",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "CountryCarSideEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CountryCar.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CountryCarSideEnum {
    Left = 'left',
    Right = 'right',
    UnknownDefaultOpenApi = '11184809'
}

