/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CountryFlags {
    'png': string | null;
    'svg': string | null;
    'alt': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "png",
            "baseName": "png",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "svg",
            "baseName": "svg",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "alt",
            "baseName": "alt",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CountryFlags.attributeTypeMap;
    }

    public constructor() {
    }
}
