/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
 * @type GetAllCountries200Response
 * Type
 * @export
 */
export type GetAllCountries200Response = Array<Array<Country>> | Array<{ [key: string]: any; }>;

/**
* @type GetAllCountries200ResponseClass
* @export
*/
export class GetAllCountries200ResponseClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

