/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
 * @type GetCountryByCca2200Response
 * Type
 * @export
 */
export type GetCountryByCca2200Response = Array<Country> | { [key: string]: any; };

/**
* @type GetCountryByCca2200ResponseClass
* @export
*/
export class GetCountryByCca2200ResponseClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

