/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LivewellData } from '../models/LivewellData';
import { LivewellNotFoundResponse } from '../models/LivewellNotFoundResponse';
import { HttpFile } from '../http/http';

/**
 * @type GetLivewellLevelOne200Response
 * Type
 * @export
 */
export type GetLivewellLevelOne200Response = LivewellData | LivewellNotFoundResponse;

/**
* @type GetLivewellLevelOne200ResponseClass
* @export
*/
export class GetLivewellLevelOne200ResponseClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

