/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MedicineData } from '../models/MedicineData';
import { MedicinesNotFoundResponse } from '../models/MedicinesNotFoundResponse';
import { HttpFile } from '../http/http';

/**
 * @type GetMedicineLevelOne200Response
 * Type
 * @export
 */
export type GetMedicineLevelOne200Response = MedicineData | MedicinesNotFoundResponse;

/**
* @type GetMedicineLevelOne200ResponseClass
* @export
*/
export class GetMedicineLevelOne200ResponseClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

