/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MentalHealthData } from '../models/MentalHealthData';
import { MentalHealthNotFoundResponse } from '../models/MentalHealthNotFoundResponse';
import { HttpFile } from '../http/http';

/**
 * @type GetMentalHealthLevelOne200Response
 * Type
 * @export
 */
export type GetMentalHealthLevelOne200Response = MentalHealthData | MentalHealthNotFoundResponse;

/**
* @type GetMentalHealthLevelOne200ResponseClass
* @export
*/
export class GetMentalHealthLevelOne200ResponseClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

