/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PregnancyData } from '../models/PregnancyData';
import { PregnancyNotFoundResponse } from '../models/PregnancyNotFoundResponse';
import { HttpFile } from '../http/http';

/**
 * @type GetPregnancyLevelOne200Response
 * Type
 * @export
 */
export type GetPregnancyLevelOne200Response = PregnancyData | PregnancyNotFoundResponse;

/**
* @type GetPregnancyLevelOne200ResponseClass
* @export
*/
export class GetPregnancyLevelOne200ResponseClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

