/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LivewellAbout } from '../models/LivewellAbout';
import { LivewellAboutAlternateName } from '../models/LivewellAboutAlternateName';
import { LivewellAuthor } from '../models/LivewellAuthor';
import { LivewellBreadcrumb } from '../models/LivewellBreadcrumb';
import { LivewellContentElementMainEntityInner } from '../models/LivewellContentElementMainEntityInner';
import { LivewellCopyrightHolder } from '../models/LivewellCopyrightHolder';
import { LivewellDataHasPartInner } from '../models/LivewellDataHasPartInner';
import { LivewellExpanderGroup } from '../models/LivewellExpanderGroup';
import { LivewellRelatedLink } from '../models/LivewellRelatedLink';
import { HttpFile } from '../http/http';

/**
* Live Well information returned from the stored NHS Live Well dataset. The exact content structure varies by route and query parameters.
*/
export class LivewellData {
    'context'?: string;
    'type'?: string;
    'name'?: string;
    'copyrightHolder'?: LivewellCopyrightHolder;
    'license'?: string;
    'author'?: LivewellAuthor;
    'about'?: LivewellAbout;
    'description'?: string | null;
    'url'?: string | null;
    'genre'?: Array<string>;
    'keywords'?: LivewellAboutAlternateName | null;
    'dateModified'?: Date | null;
    'lastReviewed'?: Array<string> | null;
    'hasPart'?: Array<LivewellDataHasPartInner>;
    'breadcrumb'?: LivewellBreadcrumb;
    'relatedLink'?: Array<LivewellRelatedLink> | null;
    'headline'?: string | null;
    'contentSubTypes'?: Array<string>;
    'mainEntityOfPage'?: Array<LivewellContentElementMainEntityInner>;
    'expanderGroups'?: Array<LivewellExpanderGroup> | null;
    'webpage'?: string | null;
    'id'?: number | null;
    'routeMapping'?: string | null;
    'redirect'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "context",
            "baseName": "@context",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "copyrightHolder",
            "baseName": "copyrightHolder",
            "type": "LivewellCopyrightHolder",
            "format": ""
        },
        {
            "name": "license",
            "baseName": "license",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "LivewellAuthor",
            "format": ""
        },
        {
            "name": "about",
            "baseName": "about",
            "type": "LivewellAbout",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "genre",
            "baseName": "genre",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "LivewellAboutAlternateName",
            "format": ""
        },
        {
            "name": "dateModified",
            "baseName": "dateModified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastReviewed",
            "baseName": "lastReviewed",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "hasPart",
            "baseName": "hasPart",
            "type": "Array<LivewellDataHasPartInner>",
            "format": ""
        },
        {
            "name": "breadcrumb",
            "baseName": "breadcrumb",
            "type": "LivewellBreadcrumb",
            "format": ""
        },
        {
            "name": "relatedLink",
            "baseName": "relatedLink",
            "type": "Array<LivewellRelatedLink>",
            "format": ""
        },
        {
            "name": "headline",
            "baseName": "headline",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentSubTypes",
            "baseName": "contentSubTypes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "mainEntityOfPage",
            "baseName": "mainEntityOfPage",
            "type": "Array<LivewellContentElementMainEntityInner>",
            "format": ""
        },
        {
            "name": "expanderGroups",
            "baseName": "expander_groups",
            "type": "Array<LivewellExpanderGroup>",
            "format": ""
        },
        {
            "name": "webpage",
            "baseName": "webpage",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "routeMapping",
            "baseName": "route_mapping",
            "type": "string",
            "format": ""
        },
        {
            "name": "redirect",
            "baseName": "redirect",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LivewellData.attributeTypeMap;
    }

    public constructor() {
    }
}
