/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LivewellContentElement } from '../models/LivewellContentElement';
import { LivewellVideoObject } from '../models/LivewellVideoObject';
import { HttpFile } from '../http/http';

/**
 * @type LivewellContentElementMainEntityInner
 * Type
 * @export
 */
export type LivewellContentElementMainEntityInner = LivewellContentElement | LivewellVideoObject;

/**
* @type LivewellContentElementMainEntityInnerClass
* @export
*/
export class LivewellContentElementMainEntityInnerClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

