/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConditionVideoObjectIdentifier } from '../models/ConditionVideoObjectIdentifier';
import { LivewellAnswer } from '../models/LivewellAnswer';
import { LivewellAnswerLinksInner } from '../models/LivewellAnswerLinksInner';
import { LivewellContentElementMainEntityInner } from '../models/LivewellContentElementMainEntityInner';
import { HttpFile } from '../http/http';

/**
* A flexible element from an NHS Live Well page.
*/
export class LivewellContentElement {
    'type'?: string | null;
    'name'?: string | null;
    'identifier'?: ConditionVideoObjectIdentifier | null;
    'position'?: number | null;
    'headline'?: string | null;
    'description'?: string | null;
    'url'?: string | null;
    /**
    * Element content. HTML is retained by default and removed when no_html is enabled.
    */
    'text'?: string | null;
    'links'?: Array<LivewellAnswerLinksInner>;
    'acceptedAnswer'?: LivewellAnswer | null;
    'mainEntity'?: Array<LivewellContentElementMainEntityInner>;
    'mainEntityOfPage'?: Array<LivewellContentElementMainEntityInner>;
    'hasPart'?: Array<LivewellContentElementMainEntityInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "ConditionVideoObjectIdentifier",
            "format": ""
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number",
            "format": ""
        },
        {
            "name": "headline",
            "baseName": "headline",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<LivewellAnswerLinksInner>",
            "format": ""
        },
        {
            "name": "acceptedAnswer",
            "baseName": "acceptedAnswer",
            "type": "LivewellAnswer",
            "format": ""
        },
        {
            "name": "mainEntity",
            "baseName": "mainEntity",
            "type": "Array<LivewellContentElementMainEntityInner>",
            "format": ""
        },
        {
            "name": "mainEntityOfPage",
            "baseName": "mainEntityOfPage",
            "type": "Array<LivewellContentElementMainEntityInner>",
            "format": ""
        },
        {
            "name": "hasPart",
            "baseName": "hasPart",
            "type": "Array<LivewellContentElementMainEntityInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LivewellContentElement.attributeTypeMap;
    }

    public constructor() {
    }
}
