/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LivewellAnswerLinksInner } from '../models/LivewellAnswerLinksInner';
import { LivewellContentElement } from '../models/LivewellContentElement';
import { HttpFile } from '../http/http';

/**
* An answer returned within a question-style Live Well content block.
*/
export class LivewellAnswer {
    'type'?: string | null;
    /**
    * Answer text. HTML is retained by default and removed when no_html is enabled.
    */
    'text'?: string | null;
    'links'?: Array<LivewellAnswerLinksInner>;
    'mainEntity'?: Array<LivewellContentElement>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<LivewellAnswerLinksInner>",
            "format": ""
        },
        {
            "name": "mainEntity",
            "baseName": "mainEntity",
            "type": "Array<LivewellContentElement>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LivewellAnswer.attributeTypeMap;
    }

    public constructor() {
    }
}
