/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Alternative page name. The source may return a string or an array of strings.
*/
/**
 * @type LivewellAboutAlternateName
 * Type
 * @export
 */
export type LivewellAboutAlternateName = Array<string> | string;

/**
* @type LivewellAboutAlternateNameClass
    * Alternative page name. The source may return a string or an array of strings.
* @export
*/
export class LivewellAboutAlternateNameClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

