/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LivewellExpanderItem } from '../models/LivewellExpanderItem';
import { HttpFile } from '../http/http';

export class LivewellExpanderGroup {
    'heading'?: string | null;
    'items'?: Array<LivewellExpanderItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "heading",
            "baseName": "heading",
            "type": "string",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<LivewellExpanderItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LivewellExpanderGroup.attributeTypeMap;
    }

    public constructor() {
    }
}
