/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LivewellLinkObject } from '../models/LivewellLinkObject';
import { HttpFile } from '../http/http';

/**
 * @type LivewellAnswerLinksInner
 * Type
 * @export
 */
export type LivewellAnswerLinksInner = LivewellLinkObject | string;

/**
* @type LivewellAnswerLinksInnerClass
* @export
*/
export class LivewellAnswerLinksInnerClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

