/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Available routes within the Live Well service.
*/
export class LivewellRoutesResponse {
    'routes': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "routes",
            "baseName": "routes",
            "type": "Array<string>",
            "format": "uri"
        }    ];

    static getAttributeTypeMap() {
        return LivewellRoutesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
