/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LivewellBreadcrumbListItem } from '../models/LivewellBreadcrumbListItem';
import { HttpFile } from '../http/http';

export class LivewellBreadcrumb {
    'context'?: string;
    'type'?: string;
    'itemListElement'?: Array<LivewellBreadcrumbListItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "context",
            "baseName": "@context",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemListElement",
            "baseName": "itemListElement",
            "type": "Array<LivewellBreadcrumbListItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LivewellBreadcrumb.attributeTypeMap;
    }

    public constructor() {
    }
}
