/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LivewellContentElement } from '../models/LivewellContentElement';
import { HttpFile } from '../http/http';

/**
* A structured health-topic section included within a Live Well page.
*/
export class LivewellHealthTopicContent {
    'type'?: string;
    'hasHealthAspect'?: string | null;
    'url'?: string | null;
    'description'?: string | null;
    'headline'?: string | null;
    'hasPart'?: Array<LivewellContentElement>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasHealthAspect",
            "baseName": "hasHealthAspect",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "headline",
            "baseName": "headline",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasPart",
            "baseName": "hasPart",
            "type": "Array<LivewellContentElement>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LivewellHealthTopicContent.attributeTypeMap;
    }

    public constructor() {
    }
}
