/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Indicates whether the supplied value exists among the allowed values for the requested lookup. The API serializes the result as a string rather than a JSON boolean.
*/
export class LookupValidationResponse {
    'result': LookupValidationResponseResultEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "result",
            "baseName": "result",
            "type": "LookupValidationResponseResultEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LookupValidationResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum LookupValidationResponseResultEnum {
    True = 'true',
    False = 'false',
    UnknownDefaultOpenApi = '11184809'
}

