/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Allowed values for the requested validation lookup. Most lookup tables return an array of strings, while structured lookups such as race_ethnicity return an array of objects.
*/
/**
 * @type LookupAllowedValuesResponse
 * Type
 * @export
 */
export type LookupAllowedValuesResponse = Array<string> | Array<{ [key: string]: any; }>;

/**
* @type LookupAllowedValuesResponseClass
    * Allowed values for the requested validation lookup. Most lookup tables return an array of strings, while structured lookups such as race_ethnicity return an array of objects.
* @export
*/
export class LookupAllowedValuesResponseClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

