/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Extended field information returned by the all-datasets-and-fields endpoint.
*/
export class MdsAllField {
    'fieldName': string;
    'displayName': string | null;
    'dataType': string | null;
    'fieldDescription': string | null;
    /**
    * Example value associated with the field. The returned value type depends on the field definition.
    */
    'fieldExample': any | null;
    /**
    * Source associated with the MDS field.
    */
    'source': string | null;
    /**
    * Field ordering value as returned by the underlying MDS database.
    */
    'fieldOrder': any | null;
    /**
    * Maximum field length when applicable, as returned by the underlying MDS database.
    */
    'length': any | null;
    /**
    * Underlying not-null value returned directly from the MDS database.
    */
    'notNull': any | null;
    /**
    * Underlying default value returned directly from the MDS database.
    */
    '_default': any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fieldName",
            "baseName": "field_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "display_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "dataType",
            "baseName": "data_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "fieldDescription",
            "baseName": "field_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "fieldExample",
            "baseName": "field_example",
            "type": "any",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string",
            "format": ""
        },
        {
            "name": "fieldOrder",
            "baseName": "field_order",
            "type": "any",
            "format": ""
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "any",
            "format": ""
        },
        {
            "name": "notNull",
            "baseName": "not_null",
            "type": "any",
            "format": ""
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MdsAllField.attributeTypeMap;
    }

    public constructor() {
    }
}
