/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MdsAllField } from '../models/MdsAllField';
import { HttpFile } from '../http/http';

/**
* Published MDS dataset together with extended field information and the environment derived by the endpoint.
*/
export class MdsAllDatasetWithFields {
    'datasetMachineName': string;
    'datasetName': string;
    'status': string;
    'pdsFileType': MdsAllDatasetWithFieldsPdsFileTypeEnum | null;
    /**
    * Environment value derived by the endpoint from the dataset deployment flags.
    */
    'environment': MdsAllDatasetWithFieldsEnvironmentEnum;
    /**
    * Object keyed dynamically by field machine name, containing extended MDS field information.
    */
    'fields': { [key: string]: MdsAllField; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "datasetMachineName",
            "baseName": "dataset_machine_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "datasetName",
            "baseName": "dataset_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "pdsFileType",
            "baseName": "pds_file_type",
            "type": "MdsAllDatasetWithFieldsPdsFileTypeEnum",
            "format": ""
        },
        {
            "name": "environment",
            "baseName": "environment",
            "type": "MdsAllDatasetWithFieldsEnvironmentEnum",
            "format": ""
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "{ [key: string]: MdsAllField; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MdsAllDatasetWithFields.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum MdsAllDatasetWithFieldsPdsFileTypeEnum {
    SqLite = 'SQLite',
    Json = 'JSON',
    UnknownDefaultOpenApi = '11184809'
}
export enum MdsAllDatasetWithFieldsEnvironmentEnum {
    Production = 'Production',
    Dev = 'Dev',
    Sandbox = 'Sandbox',
    UnknownDefaultOpenApi = '11184809'
}

