/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MdsFieldType } from '../models/MdsFieldType';
import { HttpFile } from '../http/http';

/**
* Published MDS dataset together with basic information about its published fields.
*/
export class MdsDatasetWithFields {
    'datasetMachineName': string;
    'datasetName': string;
    'status': string;
    /**
    * Backing PDS file type for the dataset.
    */
    'pdsFileType': MdsDatasetWithFieldsPdsFileTypeEnum | null;
    /**
    * Object keyed dynamically by field machine name. Each property contains basic information about that field.
    */
    'fields': { [key: string]: MdsFieldType; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "datasetMachineName",
            "baseName": "dataset_machine_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "datasetName",
            "baseName": "dataset_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "pdsFileType",
            "baseName": "pds_file_type",
            "type": "MdsDatasetWithFieldsPdsFileTypeEnum",
            "format": ""
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "{ [key: string]: MdsFieldType; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MdsDatasetWithFields.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum MdsDatasetWithFieldsPdsFileTypeEnum {
    SqLite = 'SQLite',
    Json = 'JSON',
    UnknownDefaultOpenApi = '11184809'
}

