/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Summary information for a published MDS dataset.
*/
export class MdsDatasetSummary {
    'datasetMachineName': string;
    'datasetName': string;
    'status': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "datasetMachineName",
            "baseName": "dataset_machine_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "datasetName",
            "baseName": "dataset_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MdsDatasetSummary.attributeTypeMap;
    }

    public constructor() {
    }
}
