/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Field machine names containing the supplied search value. The API returns an empty string when no fields match.
*/
/**
 * @type MdsFieldSearchResponseMatchingFields
 * Type
 * @export
 */
export type MdsFieldSearchResponseMatchingFields = Array<string> | string;

/**
* @type MdsFieldSearchResponseMatchingFieldsClass
    * Field machine names containing the supplied search value. The API returns an empty string when no fields match.
* @export
*/
export class MdsFieldSearchResponseMatchingFieldsClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

