/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Extended MDS field definition returned by the dataset field-details endpoint.
*/
export class MdsFieldDetails {
    'fieldName': string;
    'displayName': string | null;
    'dataType': string | null;
    /**
    * Whether the field is marked not-null. The API serializes this value as the string true or false.
    */
    'notNull': MdsFieldDetailsNotNullEnum;
    '_default': string | null;
    'fieldDescription': string | null;
    /**
    * Example value associated with the field. The returned value type depends on the field definition.
    */
    'fieldExample': any | null;
    /**
    * Field ordering value as serialized by the current API.
    */
    'fieldOrder': string | null;
    /**
    * Maximum field length when applicable, serialized by the current API as a string.
    */
    'length': string | null;
    'status': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fieldName",
            "baseName": "field_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "display_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "dataType",
            "baseName": "data_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "notNull",
            "baseName": "not_null",
            "type": "MdsFieldDetailsNotNullEnum",
            "format": ""
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "string",
            "format": ""
        },
        {
            "name": "fieldDescription",
            "baseName": "field_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "fieldExample",
            "baseName": "field_example",
            "type": "any",
            "format": ""
        },
        {
            "name": "fieldOrder",
            "baseName": "field_order",
            "type": "string",
            "format": ""
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MdsFieldDetails.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum MdsFieldDetailsNotNullEnum {
    True = 'true',
    False = 'false',
    UnknownDefaultOpenApi = '11184809'
}

