/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MdsFieldSearchResponseMatchingFields } from '../models/MdsFieldSearchResponseMatchingFields';
import { HttpFile } from '../http/http';

/**
* Result of searching published MDS field machine names.
*/
export class MdsFieldSearchResponse {
    'searchTerm': string;
    'matchingFields': MdsFieldSearchResponseMatchingFields;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "searchTerm",
            "baseName": "search_term",
            "type": "string",
            "format": ""
        },
        {
            "name": "matchingFields",
            "baseName": "matching_fields",
            "type": "MdsFieldSearchResponseMatchingFields",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MdsFieldSearchResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
