/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* MDS summary counts. The current API serializes the database count values as strings.
*/
export class MdsSummaryCounts {
    'totalDatasets': string;
    'totalLiveDatasets': string;
    'totalFields': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "totalDatasets",
            "baseName": "total_datasets",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalLiveDatasets",
            "baseName": "total_live_datasets",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalFields",
            "baseName": "total_fields",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MdsSummaryCounts.attributeTypeMap;
    }

    public constructor() {
    }
}
