/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MdsSummaryCounts } from '../models/MdsSummaryCounts';
import { HttpFile } from '../http/http';

/**
* Summary of published MDS dataset and field counts.
*/
export class MdsSummaryResponse {
    'summary': MdsSummaryCounts;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "summary",
            "baseName": "summary",
            "type": "MdsSummaryCounts",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MdsSummaryResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
