/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementActivityType } from '../models/MeasurementActivityType';
import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Activity type or an application-level error object.
*/
/**
 * @type MeasurementActivityTypeResult
 * Type
 * @export
 */
export type MeasurementActivityTypeResult = MeasurementActivityType | MeasurementsErrorResponse;

/**
* @type MeasurementActivityTypeResultClass
    * Activity type or an application-level error object.
* @export
*/
export class MeasurementActivityTypeResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

