/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Available meal types or an application-level error object.
*/
/**
 * @type MeasurementMealTypesResult
 * Type
 * @export
 */
export type MeasurementMealTypesResult = Array<MeasurementMealType> | MeasurementsErrorResponse;

/**
* @type MeasurementMealTypesResultClass
    * Available meal types or an application-level error object.
* @export
*/
export class MeasurementMealTypesResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

