/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementsErrorDetails } from '../models/MeasurementsErrorDetails';
import { HttpFile } from '../http/http';

/**
* Application-level error returned with HTTP 200 by Measurements endpoints.
*/
export class MeasurementsErrorResponse {
    'error': MeasurementsErrorDetails;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "MeasurementsErrorDetails",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MeasurementsErrorResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
