/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementTemporalRelationToSleep } from '../models/MeasurementTemporalRelationToSleep';
import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Temporal relation to sleep or an application-level error object.
*/
/**
 * @type MeasurementTemporalRelationToSleepResult
 * Type
 * @export
 */
export type MeasurementTemporalRelationToSleepResult = MeasurementTemporalRelationToSleep | MeasurementsErrorResponse;

/**
* @type MeasurementTemporalRelationToSleepResultClass
    * Temporal relation to sleep or an application-level error object.
* @export
*/
export class MeasurementTemporalRelationToSleepResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

