/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementBodyTemperatureLocation } from '../models/MeasurementBodyTemperatureLocation';
import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Body temperature location or an application-level error object.
*/
/**
 * @type MeasurementBodyTemperatureLocationResult
 * Type
 * @export
 */
export type MeasurementBodyTemperatureLocationResult = MeasurementBodyTemperatureLocation | MeasurementsErrorResponse;

/**
* @type MeasurementBodyTemperatureLocationResultClass
    * Body temperature location or an application-level error object.
* @export
*/
export class MeasurementBodyTemperatureLocationResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

