/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementCervicalMucusTexture } from '../models/MeasurementCervicalMucusTexture';
import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Cervical mucus texture or an application-level error object.
*/
/**
 * @type MeasurementCervicalMucusTextureResult
 * Type
 * @export
 */
export type MeasurementCervicalMucusTextureResult = MeasurementCervicalMucusTexture | MeasurementsErrorResponse;

/**
* @type MeasurementCervicalMucusTextureResultClass
    * Cervical mucus texture or an application-level error object.
* @export
*/
export class MeasurementCervicalMucusTextureResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

