/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementMealType } from '../models/MeasurementMealType';
import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Meal type or an application-level error object.
*/
/**
 * @type MeasurementMealTypeResult
 * Type
 * @export
 */
export type MeasurementMealTypeResult = MeasurementMealType | MeasurementsErrorResponse;

/**
* @type MeasurementMealTypeResultClass
    * Meal type or an application-level error object.
* @export
*/
export class MeasurementMealTypeResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

