/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Available measurement definitions or an application-level error object.
*/
/**
 * @type MeasurementTypesResult
 * Type
 * @export
 */
export type MeasurementTypesResult = Array<MeasurementType> | MeasurementsErrorResponse;

/**
* @type MeasurementTypesResultClass
    * Available measurement definitions or an application-level error object.
* @export
*/
export class MeasurementTypesResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

