/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementGroup } from '../models/MeasurementGroup';
import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Measurement group or an application-level error object.
*/
/**
 * @type MeasurementGroupResult
 * Type
 * @export
 */
export type MeasurementGroupResult = MeasurementGroup | MeasurementsErrorResponse;

/**
* @type MeasurementGroupResultClass
    * Measurement group or an application-level error object.
* @export
*/
export class MeasurementGroupResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

