/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementCervicalFirmness } from '../models/MeasurementCervicalFirmness';
import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Cervical firmness value or an application-level error object.
*/
/**
 * @type MeasurementCervicalFirmnessResult
 * Type
 * @export
 */
export type MeasurementCervicalFirmnessResult = MeasurementCervicalFirmness | MeasurementsErrorResponse;

/**
* @type MeasurementCervicalFirmnessResultClass
    * Cervical firmness value or an application-level error object.
* @export
*/
export class MeasurementCervicalFirmnessResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

