/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementResistanceType } from '../models/MeasurementResistanceType';
import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Resistance type or an application-level error object.
*/
/**
 * @type MeasurementResistanceTypeResult
 * Type
 * @export
 */
export type MeasurementResistanceTypeResult = MeasurementResistanceType | MeasurementsErrorResponse;

/**
* @type MeasurementResistanceTypeResultClass
    * Resistance type or an application-level error object.
* @export
*/
export class MeasurementResistanceTypeResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

