/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementCervicalDilation } from '../models/MeasurementCervicalDilation';
import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Cervical dilation or an application-level error object.
*/
/**
 * @type MeasurementCervicalDilationResult
 * Type
 * @export
 */
export type MeasurementCervicalDilationResult = MeasurementCervicalDilation | MeasurementsErrorResponse;

/**
* @type MeasurementCervicalDilationResultClass
    * Cervical dilation or an application-level error object.
* @export
*/
export class MeasurementCervicalDilationResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

