/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Measurement definition including its group and unit.
*/
export class MeasurementType {
    /**
    * Measurement types.
    */
    'measurementId': string;
    'measurementName': string;
    'measurementGroup': string;
    'measurementUnit': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "measurementId",
            "baseName": "measurement_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "measurementName",
            "baseName": "measurement_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "measurementGroup",
            "baseName": "measurement_group",
            "type": "string",
            "format": ""
        },
        {
            "name": "measurementUnit",
            "baseName": "measurement_unit",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MeasurementType.attributeTypeMap;
    }

    public constructor() {
    }
}
