/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementCervicalMucusAmount } from '../models/MeasurementCervicalMucusAmount';
import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Cervical mucus amount or an application-level error object.
*/
/**
 * @type MeasurementCervicalMucusAmountResult
 * Type
 * @export
 */
export type MeasurementCervicalMucusAmountResult = MeasurementCervicalMucusAmount | MeasurementsErrorResponse;

/**
* @type MeasurementCervicalMucusAmountResultClass
    * Cervical mucus amount or an application-level error object.
* @export
*/
export class MeasurementCervicalMucusAmountResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

