/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementBodyPosition } from '../models/MeasurementBodyPosition';
import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Body position or an application-level error object.
*/
/**
 * @type MeasurementBodyPositionResult
 * Type
 * @export
 */
export type MeasurementBodyPositionResult = MeasurementBodyPosition | MeasurementsErrorResponse;

/**
* @type MeasurementBodyPositionResultClass
    * Body position or an application-level error object.
* @export
*/
export class MeasurementBodyPositionResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

