/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementCervicalPosition } from '../models/MeasurementCervicalPosition';
import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Cervical position or an application-level error object.
*/
/**
 * @type MeasurementCervicalPositionResult
 * Type
 * @export
 */
export type MeasurementCervicalPositionResult = MeasurementCervicalPosition | MeasurementsErrorResponse;

/**
* @type MeasurementCervicalPositionResultClass
    * Cervical position or an application-level error object.
* @export
*/
export class MeasurementCervicalPositionResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

