/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementExerciseType } from '../models/MeasurementExerciseType';
import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Exercise type or an application-level error object.
*/
/**
 * @type MeasurementExerciseTypeResult
 * Type
 * @export
 */
export type MeasurementExerciseTypeResult = MeasurementExerciseType | MeasurementsErrorResponse;

/**
* @type MeasurementExerciseTypeResultClass
    * Exercise type or an application-level error object.
* @export
*/
export class MeasurementExerciseTypeResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

