/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementBloodPressureMeasurement } from '../models/MeasurementBloodPressureMeasurement';
import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Blood pressure measurement type or an application-level error object.
*/
/**
 * @type MeasurementBloodPressureMeasurementResult
 * Type
 * @export
 */
export type MeasurementBloodPressureMeasurementResult = MeasurementBloodPressureMeasurement | MeasurementsErrorResponse;

/**
* @type MeasurementBloodPressureMeasurementResultClass
    * Blood pressure measurement type or an application-level error object.
* @export
*/
export class MeasurementBloodPressureMeasurementResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

