/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Available temporal relations to sleep or an application-level error object.
*/
/**
 * @type MeasurementTemporalRelationsToSleepResult
 * Type
 * @export
 */
export type MeasurementTemporalRelationsToSleepResult = Array<MeasurementTemporalRelationToSleep> | MeasurementsErrorResponse;

/**
* @type MeasurementTemporalRelationsToSleepResultClass
    * Available temporal relations to sleep or an application-level error object.
* @export
*/
export class MeasurementTemporalRelationsToSleepResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

