/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Available resistance types or an application-level error object.
*/
/**
 * @type MeasurementResistanceTypesResult
 * Type
 * @export
 */
export type MeasurementResistanceTypesResult = Array<MeasurementResistanceType> | MeasurementsErrorResponse;

/**
* @type MeasurementResistanceTypesResultClass
    * Available resistance types or an application-level error object.
* @export
*/
export class MeasurementResistanceTypesResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

