/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MeasurementBloodSpecimenSource } from '../models/MeasurementBloodSpecimenSource';
import { MeasurementsErrorResponse } from '../models/MeasurementsErrorResponse';
import { HttpFile } from '../http/http';

/**
* Blood specimen source or an application-level error object.
*/
/**
 * @type MeasurementBloodSpecimenSourceResult
 * Type
 * @export
 */
export type MeasurementBloodSpecimenSourceResult = MeasurementBloodSpecimenSource | MeasurementsErrorResponse;

/**
* @type MeasurementBloodSpecimenSourceResultClass
    * Blood specimen source or an application-level error object.
* @export
*/
export class MeasurementBloodSpecimenSourceResultClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

