/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MedicineAnswerLinksInner } from '../models/MedicineAnswerLinksInner';
import { HttpFile } from '../http/http';

/**
* Flexible nested entity that may occur inside a content element\'s mainEntity property.
*/
export class MedicineNestedEntity {
    'mainEntity'?: string | null;
    'text'?: string | null;
    'links'?: Array<MedicineAnswerLinksInner> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mainEntity",
            "baseName": "mainEntity",
            "type": "string",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<MedicineAnswerLinksInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MedicineNestedEntity.attributeTypeMap;
    }

    public constructor() {
    }
}
