/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MedicineLinkObject } from '../models/MedicineLinkObject';
import { HttpFile } from '../http/http';

/**
 * @type MedicineAnswerLinksInner
 * Type
 * @export
 */
export type MedicineAnswerLinksInner = MedicineLinkObject | string;

/**
* @type MedicineAnswerLinksInnerClass
* @export
*/
export class MedicineAnswerLinksInnerClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

