/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MedicineNestedEntity } from '../models/MedicineNestedEntity';
import { HttpFile } from '../http/http';

/**
* Nested content. The implementation can encounter a string, a single entity object or an array of entities.
*/
/**
 * @type MedicineContentElementMainEntity
 * Type
 * @export
 */
export type MedicineContentElementMainEntity = Array<MedicineNestedEntity> | MedicineNestedEntity | string;

/**
* @type MedicineContentElementMainEntityClass
    * Nested content. The implementation can encounter a string, a single entity object or an array of entities.
* @export
*/
export class MedicineContentElementMainEntityClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}


