/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MedicineAnswerLinksInner } from '../models/MedicineAnswerLinksInner';
import { MedicineContentElement } from '../models/MedicineContentElement';
import { HttpFile } from '../http/http';

/**
* An answer returned within a Medicines question. Answers may contain text directly, nested content elements in mainEntity, or both.
*/
export class MedicineAnswer {
    'type'?: string | null;
    /**
    * Answer text when supplied directly by the source. HTML is retained by default and removed when no_html is enabled.
    */
    'text'?: string | null;
    'links'?: Array<MedicineAnswerLinksInner>;
    /**
    * Nested answer content.
    */
    'mainEntity'?: Array<MedicineContentElement>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<MedicineAnswerLinksInner>",
            "format": ""
        },
        {
            "name": "mainEntity",
            "baseName": "mainEntity",
            "type": "Array<MedicineContentElement>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MedicineAnswer.attributeTypeMap;
    }

    public constructor() {
    }
}
