/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LivewellAboutAlternateName } from '../models/LivewellAboutAlternateName';
import { MedicineAbout } from '../models/MedicineAbout';
import { MedicineAuthor } from '../models/MedicineAuthor';
import { MedicineBreadcrumb } from '../models/MedicineBreadcrumb';
import { MedicineContentElement } from '../models/MedicineContentElement';
import { MedicineCopyrightHolder } from '../models/MedicineCopyrightHolder';
import { MedicineHealthTopicContent } from '../models/MedicineHealthTopicContent';
import { MedicineRelatedLink } from '../models/MedicineRelatedLink';
import { HttpFile } from '../http/http';

/**
* Medicine information returned from the stored NHS Medicines dataset. The exact structure varies by requested route and query parameters.
*/
export class MedicineData {
    'context'?: string;
    'type'?: string;
    'name'?: string;
    'copyrightHolder'?: MedicineCopyrightHolder;
    'license'?: string;
    'author'?: MedicineAuthor;
    'about'?: MedicineAbout;
    'description'?: string | null;
    'url'?: string | null;
    'genre'?: Array<string>;
    'keywords'?: LivewellAboutAlternateName | null;
    'dateModified'?: Date | null;
    'lastReviewed'?: Array<string> | null;
    'hasPart'?: Array<MedicineHealthTopicContent>;
    'breadcrumb'?: MedicineBreadcrumb;
    'relatedLink'?: Array<MedicineRelatedLink> | null;
    'headline'?: string | null;
    'contentSubTypes'?: Array<string>;
    'mainEntityOfPage'?: Array<MedicineContentElement>;
    'webpage'?: string | null;
    'id'?: number | null;
    'routeMapping'?: string | null;
    'redirect'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "context",
            "baseName": "@context",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "copyrightHolder",
            "baseName": "copyrightHolder",
            "type": "MedicineCopyrightHolder",
            "format": ""
        },
        {
            "name": "license",
            "baseName": "license",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "MedicineAuthor",
            "format": ""
        },
        {
            "name": "about",
            "baseName": "about",
            "type": "MedicineAbout",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "genre",
            "baseName": "genre",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "LivewellAboutAlternateName",
            "format": ""
        },
        {
            "name": "dateModified",
            "baseName": "dateModified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastReviewed",
            "baseName": "lastReviewed",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "hasPart",
            "baseName": "hasPart",
            "type": "Array<MedicineHealthTopicContent>",
            "format": ""
        },
        {
            "name": "breadcrumb",
            "baseName": "breadcrumb",
            "type": "MedicineBreadcrumb",
            "format": ""
        },
        {
            "name": "relatedLink",
            "baseName": "relatedLink",
            "type": "Array<MedicineRelatedLink>",
            "format": ""
        },
        {
            "name": "headline",
            "baseName": "headline",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentSubTypes",
            "baseName": "contentSubTypes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "mainEntityOfPage",
            "baseName": "mainEntityOfPage",
            "type": "Array<MedicineContentElement>",
            "format": ""
        },
        {
            "name": "webpage",
            "baseName": "webpage",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "routeMapping",
            "baseName": "route_mapping",
            "type": "string",
            "format": ""
        },
        {
            "name": "redirect",
            "baseName": "redirect",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MedicineData.attributeTypeMap;
    }

    public constructor() {
    }
}
