/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConditionVideoObjectIdentifier } from '../models/ConditionVideoObjectIdentifier';
import { MedicineAnswer } from '../models/MedicineAnswer';
import { MedicineAnswerLinksInner } from '../models/MedicineAnswerLinksInner';
import { MedicineContentElementMainEntity } from '../models/MedicineContentElementMainEntity';
import { HttpFile } from '../http/http';

/**
* A flexible content element from an NHS Medicines page.
*/
export class MedicineContentElement {
    'type'?: string | null;
    'name'?: string | null;
    'identifier'?: ConditionVideoObjectIdentifier | null;
    'position'?: number | null;
    'headline'?: string | null;
    'description'?: string | null;
    'url'?: string | null;
    /**
    * Content or question text. HTML is retained by default and removed when no_html is enabled.
    */
    'text'?: string | null;
    /**
    * Caption content when supplied by the source. This is processed by the same content formatter as text.
    */
    'caption'?: string | null;
    /**
    * Credit content when supplied by the source. This is processed by the same content formatter as text.
    */
    'credit'?: string | null;
    'links'?: Array<MedicineAnswerLinksInner>;
    'acceptedAnswer'?: MedicineAnswer | null;
    'mainEntity'?: MedicineContentElementMainEntity | null;
    /**
    * Nested page elements.
    */
    'mainEntityOfPage'?: Array<MedicineContentElement>;
    /**
    * Nested content elements duplicated or grouped under hasPart by the source data.
    */
    'hasPart'?: Array<MedicineContentElement>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "ConditionVideoObjectIdentifier",
            "format": ""
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number",
            "format": ""
        },
        {
            "name": "headline",
            "baseName": "headline",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "caption",
            "baseName": "caption",
            "type": "string",
            "format": ""
        },
        {
            "name": "credit",
            "baseName": "credit",
            "type": "string",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<MedicineAnswerLinksInner>",
            "format": ""
        },
        {
            "name": "acceptedAnswer",
            "baseName": "acceptedAnswer",
            "type": "MedicineAnswer",
            "format": ""
        },
        {
            "name": "mainEntity",
            "baseName": "mainEntity",
            "type": "MedicineContentElementMainEntity",
            "format": ""
        },
        {
            "name": "mainEntityOfPage",
            "baseName": "mainEntityOfPage",
            "type": "Array<MedicineContentElement>",
            "format": ""
        },
        {
            "name": "hasPart",
            "baseName": "hasPart",
            "type": "Array<MedicineContentElement>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MedicineContentElement.attributeTypeMap;
    }

    public constructor() {
    }
}
