/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MentalHealthContentElement } from '../models/MentalHealthContentElement';
import { MentalHealthVideoObject } from '../models/MentalHealthVideoObject';
import { HttpFile } from '../http/http';

/**
 * @type MentalHealthContentElementMainEntityOfPageInner
 * Type
 * @export
 */
export type MentalHealthContentElementMainEntityOfPageInner = MentalHealthContentElement | MentalHealthVideoObject;

/**
* @type MentalHealthContentElementMainEntityOfPageInnerClass
* @export
*/
export class MentalHealthContentElementMainEntityOfPageInnerClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

