/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MentalHealthAnswerLinksInner } from '../models/MentalHealthAnswerLinksInner';
import { HttpFile } from '../http/http';

/**
* Object form of a nested mainEntity value.
*/
export class MentalHealthMainEntityObject {
    'mainEntity'?: string | null;
    'text'?: string | null;
    'links'?: Array<MentalHealthAnswerLinksInner> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mainEntity",
            "baseName": "mainEntity",
            "type": "string",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<MentalHealthAnswerLinksInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MentalHealthMainEntityObject.attributeTypeMap;
    }

    public constructor() {
    }
}
