/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MentalHealthBreadcrumbItemData } from '../models/MentalHealthBreadcrumbItemData';
import { HttpFile } from '../http/http';

export class MentalHealthBreadcrumbListItem {
    'type'?: string;
    'position'?: number;
    'item'?: MentalHealthBreadcrumbItemData;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number",
            "format": ""
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "MentalHealthBreadcrumbItemData",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MentalHealthBreadcrumbListItem.attributeTypeMap;
    }

    public constructor() {
    }
}
