/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MentalHealthMainEntityObject } from '../models/MentalHealthMainEntityObject';
import { HttpFile } from '../http/http';

/**
* Nested content. The implementation can encounter a string, a single object or an array of objects.
*/
/**
 * @type MentalHealthContentElementMainEntity
 * Type
 * @export
 */
export type MentalHealthContentElementMainEntity = Array<MentalHealthMainEntityObject> | MentalHealthMainEntityObject | string;

/**
* @type MentalHealthContentElementMainEntityClass
    * Nested content. The implementation can encounter a string, a single object or an array of objects.
* @export
*/
export class MentalHealthContentElementMainEntityClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}


