/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MentalHealthLinkObject } from '../models/MentalHealthLinkObject';
import { HttpFile } from '../http/http';

/**
 * @type MentalHealthAnswerLinksInner
 * Type
 * @export
 */
export type MentalHealthAnswerLinksInner = MentalHealthLinkObject | string;

/**
* @type MentalHealthAnswerLinksInnerClass
* @export
*/
export class MentalHealthAnswerLinksInnerClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

