/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LivewellAboutAlternateName } from '../models/LivewellAboutAlternateName';
import { MentalHealthAbout } from '../models/MentalHealthAbout';
import { MentalHealthAuthor } from '../models/MentalHealthAuthor';
import { MentalHealthBreadcrumb } from '../models/MentalHealthBreadcrumb';
import { MentalHealthContentElementMainEntityOfPageInner } from '../models/MentalHealthContentElementMainEntityOfPageInner';
import { MentalHealthCopyrightHolder } from '../models/MentalHealthCopyrightHolder';
import { MentalHealthExpanderGroup } from '../models/MentalHealthExpanderGroup';
import { MentalHealthHealthTopicContent } from '../models/MentalHealthHealthTopicContent';
import { MentalHealthRelatedLink } from '../models/MentalHealthRelatedLink';
import { HttpFile } from '../http/http';

/**
* Mental Health information returned from the stored NHS Mental Health dataset. The exact content structure varies by route.
*/
export class MentalHealthData {
    'context'?: string;
    'type'?: string;
    'name'?: string;
    'copyrightHolder'?: MentalHealthCopyrightHolder;
    'license'?: string;
    'author'?: MentalHealthAuthor;
    'about'?: MentalHealthAbout;
    'description'?: string | null;
    'url'?: string | null;
    'genre'?: Array<string>;
    'keywords'?: LivewellAboutAlternateName | null;
    'dateModified'?: Date | null;
    'lastReviewed'?: Array<string> | null;
    'hasPart'?: Array<MentalHealthHealthTopicContent>;
    'breadcrumb'?: MentalHealthBreadcrumb;
    'relatedLink'?: Array<MentalHealthRelatedLink> | null;
    'headline'?: string | null;
    'contentSubTypes'?: Array<string>;
    'mainEntityOfPage'?: Array<MentalHealthContentElementMainEntityOfPageInner>;
    'expanderGroups'?: Array<MentalHealthExpanderGroup> | null;
    'webpage'?: string | null;
    'id'?: number | null;
    'routeMapping'?: string | null;
    'redirect'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "context",
            "baseName": "@context",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "copyrightHolder",
            "baseName": "copyrightHolder",
            "type": "MentalHealthCopyrightHolder",
            "format": ""
        },
        {
            "name": "license",
            "baseName": "license",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "MentalHealthAuthor",
            "format": ""
        },
        {
            "name": "about",
            "baseName": "about",
            "type": "MentalHealthAbout",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "genre",
            "baseName": "genre",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "LivewellAboutAlternateName",
            "format": ""
        },
        {
            "name": "dateModified",
            "baseName": "dateModified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastReviewed",
            "baseName": "lastReviewed",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "hasPart",
            "baseName": "hasPart",
            "type": "Array<MentalHealthHealthTopicContent>",
            "format": ""
        },
        {
            "name": "breadcrumb",
            "baseName": "breadcrumb",
            "type": "MentalHealthBreadcrumb",
            "format": ""
        },
        {
            "name": "relatedLink",
            "baseName": "relatedLink",
            "type": "Array<MentalHealthRelatedLink>",
            "format": ""
        },
        {
            "name": "headline",
            "baseName": "headline",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentSubTypes",
            "baseName": "contentSubTypes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "mainEntityOfPage",
            "baseName": "mainEntityOfPage",
            "type": "Array<MentalHealthContentElementMainEntityOfPageInner>",
            "format": ""
        },
        {
            "name": "expanderGroups",
            "baseName": "expander_groups",
            "type": "Array<MentalHealthExpanderGroup>",
            "format": ""
        },
        {
            "name": "webpage",
            "baseName": "webpage",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "routeMapping",
            "baseName": "route_mapping",
            "type": "string",
            "format": ""
        },
        {
            "name": "redirect",
            "baseName": "redirect",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MentalHealthData.attributeTypeMap;
    }

    public constructor() {
    }
}
