/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Application-level response returned with HTTP 200 when the requested Mental Health route does not exist.
*/
export class MentalHealthNotFoundResponse {
    'message': MentalHealthNotFoundResponseMessageEnum;
    'indexOfMentalHealthRoutes': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "MentalHealthNotFoundResponseMessageEnum",
            "format": ""
        },
        {
            "name": "indexOfMentalHealthRoutes",
            "baseName": "index of Mental Health routes",
            "type": "string",
            "format": "uri"
        }    ];

    static getAttributeTypeMap() {
        return MentalHealthNotFoundResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum MentalHealthNotFoundResponseMessageEnum {
    TheRequestedDataDoesNotExist = 'the requested data does not exist',
    UnknownDefaultOpenApi = '11184809'
}

