/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConditionVideoObjectIdentifier } from '../models/ConditionVideoObjectIdentifier';
import { HttpFile } from '../http/http';

/**
* Video content included within a Mental Health page. VideoObject entries are passed through without content formatting.
*/
export class MentalHealthVideoObject {
    'type'?: string;
    'name'?: string | null;
    'embedUrl'?: string | null;
    'contentUrl'?: string | null;
    /**
    * ISO 8601 media duration.
    */
    'duration'?: string | null;
    'position'?: number | null;
    'identifier'?: ConditionVideoObjectIdentifier | null;
    'alternateName'?: string | null;
    'description'?: string | null;
    'uploadDate'?: Date | null;
    'lastReviewed'?: Array<string> | null;
    'thumbnailUrl'?: string | null;
    'text'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "embedUrl",
            "baseName": "embedUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentUrl",
            "baseName": "contentUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "string",
            "format": ""
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "ConditionVideoObjectIdentifier",
            "format": ""
        },
        {
            "name": "alternateName",
            "baseName": "alternateName",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "uploadDate",
            "baseName": "uploadDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastReviewed",
            "baseName": "lastReviewed",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "thumbnailUrl",
            "baseName": "thumbnailUrl",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MentalHealthVideoObject.attributeTypeMap;
    }

    public constructor() {
    }
}
