/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConditionVideoObjectIdentifier } from '../models/ConditionVideoObjectIdentifier';
import { MentalHealthAnswer } from '../models/MentalHealthAnswer';
import { MentalHealthAnswerLinksInner } from '../models/MentalHealthAnswerLinksInner';
import { MentalHealthContentElementMainEntity } from '../models/MentalHealthContentElementMainEntity';
import { MentalHealthContentElementMainEntityOfPageInner } from '../models/MentalHealthContentElementMainEntityOfPageInner';
import { HttpFile } from '../http/http';

/**
* A flexible element from an NHS Mental Health page.
*/
export class MentalHealthContentElement {
    /**
    * Schema.org element type.
    */
    'type'?: string | null;
    'name'?: string | null;
    'identifier'?: ConditionVideoObjectIdentifier | null;
    'position'?: number | null;
    'headline'?: string | null;
    'description'?: string | null;
    'url'?: string | null;
    /**
    * Element content. HTML is retained by default and removed when no_html is enabled.
    */
    'text'?: string | null;
    /**
    * Caption content when supplied by the source. This is processed by the content formatter.
    */
    'caption'?: string | null;
    /**
    * Credit content when supplied by the source. This is processed by the content formatter.
    */
    'credit'?: string | null;
    'links'?: Array<MentalHealthAnswerLinksInner> | null;
    'acceptedAnswer'?: MentalHealthAnswer | null;
    'mainEntity'?: MentalHealthContentElementMainEntity | null;
    'mainEntityOfPage'?: Array<MentalHealthContentElementMainEntityOfPageInner> | null;
    'hasPart'?: Array<MentalHealthContentElementMainEntityOfPageInner> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "ConditionVideoObjectIdentifier",
            "format": ""
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number",
            "format": ""
        },
        {
            "name": "headline",
            "baseName": "headline",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "caption",
            "baseName": "caption",
            "type": "string",
            "format": ""
        },
        {
            "name": "credit",
            "baseName": "credit",
            "type": "string",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<MentalHealthAnswerLinksInner>",
            "format": ""
        },
        {
            "name": "acceptedAnswer",
            "baseName": "acceptedAnswer",
            "type": "MentalHealthAnswer",
            "format": ""
        },
        {
            "name": "mainEntity",
            "baseName": "mainEntity",
            "type": "MentalHealthContentElementMainEntity",
            "format": ""
        },
        {
            "name": "mainEntityOfPage",
            "baseName": "mainEntityOfPage",
            "type": "Array<MentalHealthContentElementMainEntityOfPageInner>",
            "format": ""
        },
        {
            "name": "hasPart",
            "baseName": "hasPart",
            "type": "Array<MentalHealthContentElementMainEntityOfPageInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MentalHealthContentElement.attributeTypeMap;
    }

    public constructor() {
    }
}
