/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Mydex Template System feature record. The endpoint selects the complete features database record, so additional database fields may also be present.
*/
export class MtsFeatureRecord {
    'id': string;
    'featureName': string;
    'featureMachineName': string;
    'featureGroup': string;
    'route': string;
    'featureGroupMachineName': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "featureName",
            "baseName": "feature_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "featureMachineName",
            "baseName": "feature_machine_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "featureGroup",
            "baseName": "feature_group",
            "type": "string",
            "format": ""
        },
        {
            "name": "route",
            "baseName": "route",
            "type": "string",
            "format": ""
        },
        {
            "name": "featureGroupMachineName",
            "baseName": "feature_group_machine_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MtsFeatureRecord.attributeTypeMap;
    }

    public constructor() {
    }
}
