/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Mydex Template System template, module and subsection record. The endpoint selects the complete templates_features database record, so additional database fields may also be present.
*/
export class MtsTemplateRecord {
    'id': string;
    'templateName': string;
    'templateMachineName': string;
    'moduleName': string;
    'moduleRoute': string;
    'fullRoute': string;
    'moduleSubsection': string;
    'subsectionRoute': string;
    'route': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "templateName",
            "baseName": "template_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "templateMachineName",
            "baseName": "template_machine_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "moduleName",
            "baseName": "module_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "moduleRoute",
            "baseName": "module_route",
            "type": "string",
            "format": ""
        },
        {
            "name": "fullRoute",
            "baseName": "full_route",
            "type": "string",
            "format": ""
        },
        {
            "name": "moduleSubsection",
            "baseName": "module_subsection",
            "type": "string",
            "format": ""
        },
        {
            "name": "subsectionRoute",
            "baseName": "subsection_route",
            "type": "string",
            "format": ""
        },
        {
            "name": "route",
            "baseName": "route",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MtsTemplateRecord.attributeTypeMap;
    }

    public constructor() {
    }
}
