/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SearchPagination } from '../models/SearchPagination';
import { SearchResultItem } from '../models/SearchResultItem';
import { HttpFile } from '../http/http';

/**
* Successful paginated search response returned when the all query parameter is absent.
*/
export class PaginatedSearchResponse {
    /**
    * Total number of database rows matching the search. PDO currently returns this count as a string.
    */
    'count': string;
    /**
    * Matching MRD search records.
    */
    'data': Array<SearchResultItem>;
    'pagination': SearchPagination;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<SearchResultItem>",
            "format": ""
        },
        {
            "name": "pagination",
            "baseName": "pagination",
            "type": "SearchPagination",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaginatedSearchResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
