/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConditionVideoObjectIdentifier } from '../models/ConditionVideoObjectIdentifier';
import { PregnancyAnswer } from '../models/PregnancyAnswer';
import { PregnancyAnswerLinksInner } from '../models/PregnancyAnswerLinksInner';
import { PregnancyContentElementMainEntity } from '../models/PregnancyContentElementMainEntity';
import { PregnancyContentElementMainEntityOfPageInner } from '../models/PregnancyContentElementMainEntityOfPageInner';
import { HttpFile } from '../http/http';

/**
* A flexible element from an NHS Pregnancy page. The exact properties vary according to the source content type.
*/
export class PregnancyContentElement {
    'type'?: string | null;
    'name'?: string | null;
    'identifier'?: ConditionVideoObjectIdentifier | null;
    'position'?: number | null;
    /**
    * Element heading. Empty strings are valid.
    */
    'headline'?: string | null;
    'description'?: string | null;
    /**
    * Element URL. MRD API URLs are normally returned by default and NHS URLs are returned when nhs_links is enabled.
    */
    'url'?: string | null;
    /**
    * Element content. HTML is retained by default. When no_html is enabled, markup is removed and extracted links may be moved into links.
    */
    'text'?: string | null;
    /**
    * Caption content when supplied by the source. This content is processed using the selected content formatter.
    */
    'caption'?: string | null;
    /**
    * Credit content when supplied by the source. This content is processed using the selected content formatter.
    */
    'credit'?: string | null;
    /**
    * Links extracted while formatting text, caption, credit or nested content.
    */
    'links'?: Array<PregnancyAnswerLinksInner> | null;
    'acceptedAnswer'?: PregnancyAnswer | null;
    'mainEntity'?: PregnancyContentElementMainEntity | null;
    /**
    * Nested Pregnancy page content.
    */
    'mainEntityOfPage'?: Array<PregnancyContentElementMainEntityOfPageInner> | null;
    /**
    * Nested Pregnancy content.
    */
    'hasPart'?: Array<PregnancyContentElement> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "ConditionVideoObjectIdentifier",
            "format": ""
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number",
            "format": ""
        },
        {
            "name": "headline",
            "baseName": "headline",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "caption",
            "baseName": "caption",
            "type": "string",
            "format": ""
        },
        {
            "name": "credit",
            "baseName": "credit",
            "type": "string",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<PregnancyAnswerLinksInner>",
            "format": ""
        },
        {
            "name": "acceptedAnswer",
            "baseName": "acceptedAnswer",
            "type": "PregnancyAnswer",
            "format": ""
        },
        {
            "name": "mainEntity",
            "baseName": "mainEntity",
            "type": "PregnancyContentElementMainEntity",
            "format": ""
        },
        {
            "name": "mainEntityOfPage",
            "baseName": "mainEntityOfPage",
            "type": "Array<PregnancyContentElementMainEntityOfPageInner>",
            "format": ""
        },
        {
            "name": "hasPart",
            "baseName": "hasPart",
            "type": "Array<PregnancyContentElement>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PregnancyContentElement.attributeTypeMap;
    }

    public constructor() {
    }
}
