/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PregnancyContentElement } from '../models/PregnancyContentElement';
import { PregnancyVideoObject } from '../models/PregnancyVideoObject';
import { HttpFile } from '../http/http';

/**
 * @type PregnancyContentElementMainEntityOfPageInner
 * Type
 * @export
 */
export type PregnancyContentElementMainEntityOfPageInner = PregnancyContentElement | PregnancyVideoObject;

/**
* @type PregnancyContentElementMainEntityOfPageInnerClass
* @export
*/
export class PregnancyContentElementMainEntityOfPageInnerClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

