/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PregnancyContentElement } from '../models/PregnancyContentElement';
import { HttpFile } from '../http/http';

/**
* A structured health-topic section included within a Pregnancy page.
*/
export class PregnancyHealthTopicContent {
    'type'?: string;
    /**
    * Schema.org health aspect represented by the section.
    */
    'hasHealthAspect'?: string | null;
    /**
    * Section URL. By default this is normally an MRD API URL and is rewritten where eligible when nhs_links is enabled.
    */
    'url'?: string | null;
    'description'?: string | null;
    /**
    * Section heading. Empty strings are valid.
    */
    'headline'?: string | null;
    'hasPart'?: Array<PregnancyContentElement>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasHealthAspect",
            "baseName": "hasHealthAspect",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "headline",
            "baseName": "headline",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasPart",
            "baseName": "hasPart",
            "type": "Array<PregnancyContentElement>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PregnancyHealthTopicContent.attributeTypeMap;
    }

    public constructor() {
    }
}
