/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Video content supplied by the NHS Pregnancy dataset. VideoObject entries are passed through without content formatting.
*/
export class PregnancyVideoObject {
    'type'?: string;
    'name'?: string | null;
    'description'?: string | null;
    'thumbnailUrl'?: string | null;
    'uploadDate'?: string | null;
    'contentUrl'?: string | null;
    'embedUrl'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "thumbnailUrl",
            "baseName": "thumbnailUrl",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "uploadDate",
            "baseName": "uploadDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentUrl",
            "baseName": "contentUrl",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "embedUrl",
            "baseName": "embedUrl",
            "type": "string",
            "format": "uri"
        }    ];

    static getAttributeTypeMap() {
        return PregnancyVideoObject.attributeTypeMap;
    }

    public constructor() {
    }
}
