/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A structured filter used by the Pregnancy search endpoint. Every filter must contain exactly value, operator and condition.
*/
export class PregnancySearchFilter {
    /**
    * Text to search for. The value must not be empty and may contain only letters, numbers and whitespace.
    */
    'value': string;
    /**
    * Comparison operator supported by the Pregnancy search.
    */
    'operator': PregnancySearchFilterOperatorEnum;
    /**
    * Logical condition accepted by the shared search validator. The property is required but may be empty. The Pregnancy search implementation currently combines generated search clauses using AND.
    */
    'condition': PregnancySearchFilterConditionEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "PregnancySearchFilterOperatorEnum",
            "format": ""
        },
        {
            "name": "condition",
            "baseName": "condition",
            "type": "PregnancySearchFilterConditionEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PregnancySearchFilter.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum PregnancySearchFilterOperatorEnum {
    Like = 'LIKE',
    UnknownDefaultOpenApi = '11184809'
}
export enum PregnancySearchFilterConditionEnum {
    Empty = '',
    And = 'AND',
    Or = 'OR',
    UnknownDefaultOpenApi = '11184809'
}

