/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PregnancyBreadcrumbListItem } from '../models/PregnancyBreadcrumbListItem';
import { HttpFile } from '../http/http';

export class PregnancyBreadcrumb {
    'context'?: string;
    'type'?: string;
    /**
    * Breadcrumb entries associated with the Pregnancy page.
    */
    'itemListElement'?: Array<PregnancyBreadcrumbListItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "context",
            "baseName": "@context",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemListElement",
            "baseName": "itemListElement",
            "type": "Array<PregnancyBreadcrumbListItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PregnancyBreadcrumb.attributeTypeMap;
    }

    public constructor() {
    }
}
