/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PregnancyAnswerLinksInner } from '../models/PregnancyAnswerLinksInner';
import { HttpFile } from '../http/http';

/**
* Object form of a Pregnancy mainEntity value. The source structure varies between content blocks.
*/
export class PregnancyMainEntityObject {
    /**
    * Nested mainEntity text when supplied by the source.
    */
    'mainEntity'?: string | null;
    'text'?: string | null;
    'links'?: Array<PregnancyAnswerLinksInner> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mainEntity",
            "baseName": "mainEntity",
            "type": "string",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<PregnancyAnswerLinksInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PregnancyMainEntityObject.attributeTypeMap;
    }

    public constructor() {
    }
}
