/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PregnancyAnswerLinksInner } from '../models/PregnancyAnswerLinksInner';
import { HttpFile } from '../http/http';

export class PregnancyExpanderItem {
    'heading'?: string | null;
    /**
    * Expander content when supplied by the source.
    */
    'content'?: string | null;
    'links'?: Array<PregnancyAnswerLinksInner> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "heading",
            "baseName": "heading",
            "type": "string",
            "format": ""
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<PregnancyAnswerLinksInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PregnancyExpanderItem.attributeTypeMap;
    }

    public constructor() {
    }
}
