/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PregnancyMainEntityObject } from '../models/PregnancyMainEntityObject';
import { HttpFile } from '../http/http';

/**
* Nested mainEntity content. The Pregnancy source may return this as text, a single object or an array of objects.
*/
/**
 * @type PregnancyContentElementMainEntity
 * Type
 * @export
 */
export type PregnancyContentElementMainEntity = Array<PregnancyMainEntityObject> | PregnancyMainEntityObject | string;

/**
* @type PregnancyContentElementMainEntityClass
    * Nested mainEntity content. The Pregnancy source may return this as text, a single object or an array of objects.
* @export
*/
export class PregnancyContentElementMainEntityClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}


