/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LivewellAboutAlternateName } from '../models/LivewellAboutAlternateName';
import { PregnancyAbout } from '../models/PregnancyAbout';
import { PregnancyAuthor } from '../models/PregnancyAuthor';
import { PregnancyBreadcrumb } from '../models/PregnancyBreadcrumb';
import { PregnancyContentElement } from '../models/PregnancyContentElement';
import { PregnancyCopyrightHolder } from '../models/PregnancyCopyrightHolder';
import { PregnancyExpanderGroup } from '../models/PregnancyExpanderGroup';
import { PregnancyHealthTopicContent } from '../models/PregnancyHealthTopicContent';
import { PregnancyRelatedLink } from '../models/PregnancyRelatedLink';
import { HttpFile } from '../http/http';

/**
* Pregnancy information returned from the stored NHS Pregnancy dataset. The exact content structure varies by route.
*/
export class PregnancyData {
    'context'?: string;
    'type'?: string;
    'name'?: string;
    'copyrightHolder'?: PregnancyCopyrightHolder;
    'license'?: string;
    'author'?: PregnancyAuthor;
    'about'?: PregnancyAbout;
    'description'?: string | null;
    /**
    * Canonical content URL. An MRD API URL is normally returned by default and is rewritten where applicable when nhs_links is enabled.
    */
    'url'?: string | null;
    /**
    * Page genres. Pregnancy pages may return an empty array.
    */
    'genre'?: Array<string>;
    'keywords'?: LivewellAboutAlternateName | null;
    'dateModified'?: Date | null;
    /**
    * Review date and review-due date when supplied by the source.
    */
    'lastReviewed'?: Array<string> | null;
    /**
    * Structured health-topic sections. Some category pages may return an empty array.
    */
    'hasPart'?: Array<PregnancyHealthTopicContent>;
    'breadcrumb'?: PregnancyBreadcrumb;
    /**
    * Navigation links associated with the page when supplied by the source.
    */
    'relatedLink'?: Array<PregnancyRelatedLink> | null;
    /**
    * Page headline. Empty strings are valid.
    */
    'headline'?: string | null;
    'contentSubTypes'?: Array<string>;
    /**
    * Top-level Pregnancy page content. The exact elements depend on the requested NHS page.
    */
    'mainEntityOfPage'?: Array<PregnancyContentElement>;
    /**
    * Expandable content groups when supplied by the Pregnancy source data.
    */
    'expanderGroups'?: Array<PregnancyExpanderGroup> | null;
    /**
    * Original NHS webpage URL.
    */
    'webpage'?: string | null;
    'id'?: number | null;
    'routeMapping'?: string | null;
    /**
    * Redirect value from the source dataset. Empty strings are valid.
    */
    'redirect'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "context",
            "baseName": "@context",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "copyrightHolder",
            "baseName": "copyrightHolder",
            "type": "PregnancyCopyrightHolder",
            "format": ""
        },
        {
            "name": "license",
            "baseName": "license",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "PregnancyAuthor",
            "format": ""
        },
        {
            "name": "about",
            "baseName": "about",
            "type": "PregnancyAbout",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "genre",
            "baseName": "genre",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "LivewellAboutAlternateName",
            "format": ""
        },
        {
            "name": "dateModified",
            "baseName": "dateModified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastReviewed",
            "baseName": "lastReviewed",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "hasPart",
            "baseName": "hasPart",
            "type": "Array<PregnancyHealthTopicContent>",
            "format": ""
        },
        {
            "name": "breadcrumb",
            "baseName": "breadcrumb",
            "type": "PregnancyBreadcrumb",
            "format": ""
        },
        {
            "name": "relatedLink",
            "baseName": "relatedLink",
            "type": "Array<PregnancyRelatedLink>",
            "format": ""
        },
        {
            "name": "headline",
            "baseName": "headline",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentSubTypes",
            "baseName": "contentSubTypes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "mainEntityOfPage",
            "baseName": "mainEntityOfPage",
            "type": "Array<PregnancyContentElement>",
            "format": ""
        },
        {
            "name": "expanderGroups",
            "baseName": "expander_groups",
            "type": "Array<PregnancyExpanderGroup>",
            "format": ""
        },
        {
            "name": "webpage",
            "baseName": "webpage",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "routeMapping",
            "baseName": "route_mapping",
            "type": "string",
            "format": ""
        },
        {
            "name": "redirect",
            "baseName": "redirect",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PregnancyData.attributeTypeMap;
    }

    public constructor() {
    }
}
