/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PregnancyAnswerLinksInner } from '../models/PregnancyAnswerLinksInner';
import { PregnancyContentElement } from '../models/PregnancyContentElement';
import { HttpFile } from '../http/http';

/**
* An answer returned within a question-style Pregnancy content block.
*/
export class PregnancyAnswer {
    'type'?: string | null;
    /**
    * Answer text. HTML is retained by default and removed when no_html is enabled.
    */
    'text'?: string | null;
    /**
    * Links extracted while formatting the answer text.
    */
    'links'?: Array<PregnancyAnswerLinksInner> | null;
    /**
    * Nested answer content when supplied by the source.
    */
    'mainEntity'?: Array<PregnancyContentElement> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<PregnancyAnswerLinksInner>",
            "format": ""
        },
        {
            "name": "mainEntity",
            "baseName": "mainEntity",
            "type": "Array<PregnancyContentElement>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PregnancyAnswer.attributeTypeMap;
    }

    public constructor() {
    }
}
