/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Indexed MRD page matching the supplied search filters.
*/
export class SearchResultItem {
    /**
    * Indexed keyword associated with the matching page.
    */
    'keyword': string;
    /**
    * Name or heading of the matching MRD page.
    */
    'name': string;
    /**
    * Description of the matching page.
    */
    'description': string | null;
    /**
    * Absolute MRD API URL for the matching page. The model prefixes the stored route with the configured MRD host name.
    */
    'url': string;
    /**
    * MRD service scope containing the matching result.
    */
    'scope': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "keyword",
            "baseName": "keyword",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchResultItem.attributeTypeMap;
    }

    public constructor() {
    }
}
