/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Pagination metadata returned when the all query parameter is absent.
*/
export class SearchPagination {
    'currentPage': number;
    'totalPages': number;
    'nextPage': number | null;
    'previousPage': number | null;
    'lastPage': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "currentPage",
            "baseName": "current_page",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalPages",
            "baseName": "total_pages",
            "type": "number",
            "format": ""
        },
        {
            "name": "nextPage",
            "baseName": "next_page",
            "type": "number",
            "format": ""
        },
        {
            "name": "previousPage",
            "baseName": "previous_page",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastPage",
            "baseName": "last_page",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchPagination.attributeTypeMap;
    }

    public constructor() {
    }
}
