/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AlissAccessibilityFeaturesFilter } from '../models/AlissAccessibilityFeaturesFilter';
import { AlissCategoriesFilter } from '../models/AlissCategoriesFilter';
import { AlissCommunityGroupsFilter } from '../models/AlissCommunityGroupsFilter';
import { AlissLocationsFilter } from '../models/AlissLocationsFilter';
import { AlissOrganisationsFilter } from '../models/AlissOrganisationsFilter';
import { AlissServiceAreasFilter } from '../models/AlissServiceAreasFilter';
import { AlissServicesFilter } from '../models/AlissServicesFilter';
import { HttpFile } from '../http/http';

export class SearchAlissServicesFiltersParameter {
    'services'?: Array<AlissServicesFilter>;
    'organisations'?: Array<AlissOrganisationsFilter>;
    'categories'?: Array<AlissCategoriesFilter>;
    'serviceAreas'?: Array<AlissServiceAreasFilter>;
    'locations'?: Array<AlissLocationsFilter>;
    'accessibilityFeatures'?: Array<AlissAccessibilityFeaturesFilter>;
    'communityGroups'?: Array<AlissCommunityGroupsFilter>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "services",
            "baseName": "services",
            "type": "Array<AlissServicesFilter>",
            "format": ""
        },
        {
            "name": "organisations",
            "baseName": "organisations",
            "type": "Array<AlissOrganisationsFilter>",
            "format": ""
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<AlissCategoriesFilter>",
            "format": ""
        },
        {
            "name": "serviceAreas",
            "baseName": "service_areas",
            "type": "Array<AlissServiceAreasFilter>",
            "format": ""
        },
        {
            "name": "locations",
            "baseName": "locations",
            "type": "Array<AlissLocationsFilter>",
            "format": ""
        },
        {
            "name": "accessibilityFeatures",
            "baseName": "accessibility_features",
            "type": "Array<AlissAccessibilityFeaturesFilter>",
            "format": ""
        },
        {
            "name": "communityGroups",
            "baseName": "community_groups",
            "type": "Array<AlissCommunityGroupsFilter>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchAlissServicesFiltersParameter.attributeTypeMap;
    }

    public constructor() {
    }
}
