/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaginatedSearchResponse } from '../models/PaginatedSearchResponse';
import { SearchErrorResponse } from '../models/SearchErrorResponse';
import { UnpaginatedSearchResponse } from '../models/UnpaginatedSearchResponse';
import { HttpFile } from '../http/http';

/**
 * @type SearchMrd200Response
 * Type
 * @export
 */
export type SearchMrd200Response = PaginatedSearchResponse | SearchErrorResponse | UnpaginatedSearchResponse;

/**
* @type SearchMrd200ResponseClass
* @export
*/
export class SearchMrd200ResponseClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}


