/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SearchErrorDetails } from '../models/SearchErrorDetails';
import { HttpFile } from '../http/http';

/**
* Application-level Search error returned with HTTP 200.
*/
export class SearchErrorResponse {
    'error': SearchErrorDetails;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "SearchErrorDetails",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchErrorResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
