/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An indexed Search filter. operator and condition are required. keyword, description or both may be supplied. Filter 0 has the additional runtime requirement that keyword must be present.
*/
export class SearchFilter {
    /**
    * Optional keyword value to search. A non-empty value may contain letters, numbers, commas, spaces and hyphens and cannot consist only of whitespace.
    */
    'keyword'?: string;
    /**
    * Optional page-description value to search. A non-empty value may contain letters, numbers, commas, spaces and hyphens and cannot consist only of whitespace.
    */
    'description'?: string;
    /**
    * Comparison operator used for searchable fields in this filter.
    */
    'operator': SearchFilterOperatorEnum;
    /**
    * Logical condition connecting this filter to another indexed filter. NOT is converted internally to AND NOT. The final filter should normally use an empty condition.
    */
    'condition': SearchFilterConditionEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "keyword",
            "baseName": "keyword",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "SearchFilterOperatorEnum",
            "format": ""
        },
        {
            "name": "condition",
            "baseName": "condition",
            "type": "SearchFilterConditionEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchFilter.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SearchFilterOperatorEnum {
    Equal = '=',
    Like = 'LIKE',
    UnknownDefaultOpenApi = '11184809'
}
export enum SearchFilterConditionEnum {
    Empty = '',
    And = 'AND',
    Or = 'OR',
    Not = 'NOT',
    AndNot = 'AND NOT',
    UnknownDefaultOpenApi = '11184809'
}

