/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SearchResultItem } from '../models/SearchResultItem';
import { HttpFile } from '../http/http';

/**
* Successful unpaginated search response returned when the all query parameter is present.
*/
export class UnpaginatedSearchResponse {
    /**
    * Total number of database rows matching the search. PDO currently returns this count as a string.
    */
    'count': string;
    /**
    * All matching MRD search records.
    */
    'data': Array<SearchResultItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<SearchResultItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UnpaginatedSearchResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
