/**
 * MRD API
 * API for retrieving Master Reference Data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ValidationsErrorDetails } from '../models/ValidationsErrorDetails';
import { HttpFile } from '../http/http';

/**
* Error returned by a Validations endpoint.
*/
export class ValidationsErrorResponse {
    'error': ValidationsErrorDetails;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "ValidationsErrorDetails",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ValidationsErrorResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
